################################################################################################
# Deleting an Entire VPC Environment in AWS                                                    #
#                                                                                              #
# By Robert J. Calva - Red Hat LATAM - 2019                                                    #
#                                                                                              #
# NOTE: just set the aws_region, aws_zone, name_zone, attendee, aws_keypair and                #
# volume_type variables as you wish!                                                           #
#                                                                                              #
# IMPORTANT: regarding storage_type information, please take a look at this link:              #
# http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html                       #
#                                                                                              #
# Variable examples:                                                                           #
#                                                                                              #
# aws_region could be: sa-east-1 or us-east-1                                                  #
# aws_zone could be: sa-east-1a, sa-east-1b, us-east-1a, us-east-1b                            #
# name_zone could be: example.com                                                              #
# volume_type could be: standard or gp2                                                        #
#                                                                                              #
# Enjoy!                                                                                       #
################################################################################################
- name: Delete an Entire VPC Environment in AWS
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:

  - name: Get Instance metadada 
  ec2_instance_facts:
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ instance_name }}"
    register: ec2_metadata

  - name: Deleting an AWS Instance
    ec2:
      instance_tags:
        Name: "{{ instance_name }}"
      region: "{{ aws_region }}"
      instance_ids: '{{ ec2_metadata.instances[0].instance_id }}'
      wait: yes
      wait_timeout: 500
      state: absent

#  - name: Deleting VPC Public Subnet Route Table for VPC {{ attendee }}
#    ec2_vpc_route_table:
#      region: "{{ aws_region }}"
#      vpc_id: "{{ vpc.vpc.id }}"
#      subnets:
#       - "{{ subnet.subnet.id }}"
#      routes:
#       - dest: 0.0.0.0/0
#         gateway_id: "{{ igw.gateway_id }}"
#    register: routetable
#    until: routetable is not failed
